In [3]:
import pandas as pd
df = pd.read_excel("Logística.xlsx")

# Criando uma coluna de atraso: tempo real - tempo previsto
df['Atraso'] = df['Tempo_real'] - df['Tempo_previsto']

# Agrupando por Origem, Destino e Filial_responsavel
resultado = (
    df.groupby(['Filial_responsavel'])
    .agg(
        Tempo_previsto_medio=('Tempo_previsto', 'mean'),
        Tempo_real_medio=('Tempo_real', 'mean'),
        Atraso_medio=('Atraso', 'mean')
    )
    .reset_index()
    .sort_values(by='Atraso_medio', ascending=False)
)
df3 = resultado.head(10)

# Exibindo os 10 maiores custos médios
display(df3)

      Filial_responsavel  Tempo_previsto_medio  Tempo_real_medio  Atraso_medio
1         Alves da Praia                   2.0               5.0           3.0
5          Araújo Alegre                   5.0               8.0           3.0
11      Cardoso da Prata                   5.0               8.0           3.0
22   Ferreira de Pimenta                   2.0               5.0           3.0
24       Fogaça do Oeste                   5.0               8.0           3.0
18                  Dias                   1.0               4.0           3.0
68             Rodrigues                   2.0               5.0           3.0
61      Pimenta da Serra                   1.0               4.0           3.0
48      Moreira da Prata                   2.0               5.0           3.0
39  Marques dos Dourados                   4.0               7.0           3.0

In [4]:
df3.to_excel("Filiais_mais_atrasos.xlsx", index=False)

: