In [16]:
import pandas as pd
import numpy as np

df = pd.read_excel("Rotas.xlsx")

In [17]:
df["Distancia_Km"] = df["Distancia_Km"].replace({-100.00: 0})
print(df["Distancia_Km"])

0     1713.32
1     1662.14
2     1762.91
3     1558.02
4        0.00
5     2293.71
6     1202.67
7     2715.72
8     2594.66
9     1916.84
10     117.01
11    1272.54
12     893.47
13    1341.65
14     374.31
15     888.52
16      45.29
17     884.91
18    1477.80
19    2811.45
20    1897.16
21       0.00
22     983.62
23     110.31
24     225.84
25       0.00
26     451.76
27      90.82
28    2729.54
29    1840.78
30    1285.72
31     704.69
32    2092.61
33    2866.26
34     397.89
35     329.74
36     605.64
37    2400.59
38     654.93
39    1362.27
40    1068.96
41    1176.16
42     791.04
43     886.99
44    2929.77
45     113.19
46    2447.82
47    1596.15
48    1209.03
49    1134.01
Name: Distancia_Km, dtype: float64

In [18]:
df['Distancia_Km'] = df['Distancia_Km'].astype(float)                           
print(df["Distancia_Km"])

0     1713.32
1     1662.14
2     1762.91
3     1558.02
4        0.00
5     2293.71
6     1202.67
7     2715.72
8     2594.66
9     1916.84
10     117.01
11    1272.54
12     893.47
13    1341.65
14     374.31
15     888.52
16      45.29
17     884.91
18    1477.80
19    2811.45
20    1897.16
21       0.00
22     983.62
23     110.31
24     225.84
25       0.00
26     451.76
27      90.82
28    2729.54
29    1840.78
30    1285.72
31     704.69
32    2092.61
33    2866.26
34     397.89
35     329.74
36     605.64
37    2400.59
38     654.93
39    1362.27
40    1068.96
41    1176.16
42     791.04
43     886.99
44    2929.77
45     113.19
46    2447.82
47    1596.15
48    1209.03
49    1134.01
Name: Distancia_Km, dtype: float64

In [19]:
media = df['Distancia_Km'].mean()
print()

In [20]:
df["Distancia_Km"] = df["Distancia_Km"].replace({0: media})
print(df["Distancia_Km"])

0     1713.3200
1     1662.1400
2     1762.9100
3     1558.0200
4     1238.2046
5     2293.7100
6     1202.6700
7     2715.7200
8     2594.6600
9     1916.8400
10     117.0100
11    1272.5400
12     893.4700
13    1341.6500
14     374.3100
15     888.5200
16      45.2900
17     884.9100
18    1477.8000
19    2811.4500
20    1897.1600
21    1238.2046
22     983.6200
23     110.3100
24     225.8400
25    1238.2046
26     451.7600
27      90.8200
28    2729.5400
29    1840.7800
30    1285.7200
31     704.6900
32    2092.6100
33    2866.2600
34     397.8900
35     329.7400
36     605.6400
37    2400.5900
38     654.9300
39    1362.2700
40    1068.9600
41    1176.1600
42     791.0400
43     886.9900
44    2929.7700
45     113.1900
46    2447.8200
47    1596.1500
48    1209.0300
49    1134.0100
Name: Distancia_Km, dtype: float64

In [21]:
df['Distancia_Km'] = df['Distancia_Km'].round(2)   

display(df)

                  Origem                 Destino  Distancia_Km Tipo_Veiculo
0                 Campos       Câmara das Pedras       1713.32     Caminhão
1                Pacheco     Montenegro de Minas       1662.14     Caminhão
2          Lima da Praia                 Almeida       1762.91       Furgão
3                  Abreu                   Abreu       1558.02     Caminhão
4                  Porto           Cirino Grande       1238.20      Carreta
5                Andrade                   Viana       2293.71      Carreta
6                da Cruz                Monteiro       1202.67     Caminhão
7        Campos do Campo          Pinto do Galho       2715.72     Caminhão
8          Rios da Praia      Souza de Rodrigues       2594.66     Caminhão
9       Siqueira da Mata                   Cunha       1916.84      Carreta
10  Fonseca dos Dourados                  Garcia        117.01     Caminhão
11                Mendes         Leão das Pedras       1272.54       Furgão
12               Barbosa        Pimenta do Galho        893.47     Caminhão
13                    Sá                Cassiano       1341.65      Carreta
14        Câmara da Mata    Peixoto de das Neves        374.31      Carreta
15                Duarte                Mendonça        888.52      Carreta
16               Andrade                   Lopes         45.29      Carreta
17              Oliveira    Casa Grande do Galho        884.91     Caminhão
18                  Leão     Nogueira das Pedras       1477.80     Caminhão
19       Moraes de Souza             Sousa Verde       2811.45      Carreta
20                 Pinto         Souza de Cirino       1897.16       Furgão
21  Santos de Montenegro                  Câmara       1238.20     Caminhão
22                Novais             Sá de Minas        983.62     Caminhão
23              Cassiano                 Moreira        110.31      Carreta
24    Castro de Carvalho             Casa Grande        225.84      Carreta
25                 Viana                    Rios       1238.20       Furgão
26               Almeida         Novais da Prata        451.76      Carreta
27             Aparecida           Cirino Grande         90.82     Caminhão
28                Cirino    Fonseca dos Dourados       2729.54       Furgão
29   Fogaça dos Dourados             Sá do Oeste       1840.78      Carreta
30         Fogaça do Sul                Teixeira       1285.72     Caminhão
31       Borges da Praia     Nascimento da Serra        704.69      Carreta
32               Correia           Leão do Campo       2092.61      Carreta
33     Silveira da Praia                 Pereira       2866.26       Furgão
34       Mendes de Minas      da Conceição de Sá        397.89      Carreta
35                Santos       da Luz de Cardoso        329.74     Caminhão
36      da Rosa da Praia         Rocha do Amparo        605.64      Carreta
37                 Souza      da Rosa das Flores       2400.59     Caminhão
38                Cirino                  da Luz        654.93     Caminhão
39       Vieira do Campo        da Cruz do Galho       1362.27       Furgão
40               Camargo  Fonseca de Vasconcelos       1068.96       Furgão
41                 Nunes                  da Luz       1176.16      Carreta
42        Lopes Paulista      Barbosa das Flores        791.04     Caminhão
43              da Cunha        da Luz de Castro        886.99      Carreta
44        Machado do Sul  das Neves dos Dourados       2929.77     Caminhão
45               Pacheco         da Luz da Prata        113.19       Furgão
46        Brito de Souza          Souza de Minas       2447.82       Furgão
47                Aragão        Camargo da Prata       1596.15      Carreta
48                Vargas                Mendonça       1209.03     Caminhão
49          Brito Alegre         Moraes do Norte       1134.01     Caminhão

In [22]:
df_dropped = df.drop(3)
print(df_dropped)

                  Origem                 Destino  Distancia_Km Tipo_Veiculo
0                 Campos       Câmara das Pedras       1713.32     Caminhão
1                Pacheco     Montenegro de Minas       1662.14     Caminhão
2          Lima da Praia                 Almeida       1762.91       Furgão
4                  Porto           Cirino Grande       1238.20      Carreta
5                Andrade                   Viana       2293.71      Carreta
6                da Cruz                Monteiro       1202.67     Caminhão
7        Campos do Campo          Pinto do Galho       2715.72     Caminhão
8          Rios da Praia      Souza de Rodrigues       2594.66     Caminhão
9       Siqueira da Mata                   Cunha       1916.84      Carreta
10  Fonseca dos Dourados                  Garcia        117.01     Caminhão
11                Mendes         Leão das Pedras       1272.54       Furgão
12               Barbosa        Pimenta do Galho        893.47     Caminhão
13                    Sá                Cassiano       1341.65      Carreta
14        Câmara da Mata    Peixoto de das Neves        374.31      Carreta
15                Duarte                Mendonça        888.52      Carreta
16               Andrade                   Lopes         45.29      Carreta
17              Oliveira    Casa Grande do Galho        884.91     Caminhão
18                  Leão     Nogueira das Pedras       1477.80     Caminhão
19       Moraes de Souza             Sousa Verde       2811.45      Carreta
20                 Pinto         Souza de Cirino       1897.16       Furgão
21  Santos de Montenegro                  Câmara       1238.20     Caminhão
22                Novais             Sá de Minas        983.62     Caminhão
23              Cassiano                 Moreira        110.31      Carreta
24    Castro de Carvalho             Casa Grande        225.84      Carreta
25                 Viana                    Rios       1238.20       Furgão
26               Almeida         Novais da Prata        451.76      Carreta
27             Aparecida           Cirino Grande         90.82     Caminhão
28                Cirino    Fonseca dos Dourados       2729.54       Furgão
29   Fogaça dos Dourados             Sá do Oeste       1840.78      Carreta
30         Fogaça do Sul                Teixeira       1285.72     Caminhão
31       Borges da Praia     Nascimento da Serra        704.69      Carreta
32               Correia           Leão do Campo       2092.61      Carreta
33     Silveira da Praia                 Pereira       2866.26       Furgão
34       Mendes de Minas      da Conceição de Sá        397.89      Carreta
35                Santos       da Luz de Cardoso        329.74     Caminhão
36      da Rosa da Praia         Rocha do Amparo        605.64      Carreta
37                 Souza      da Rosa das Flores       2400.59     Caminhão
38                Cirino                  da Luz        654.93     Caminhão
39       Vieira do Campo        da Cruz do Galho       1362.27       Furgão
40               Camargo  Fonseca de Vasconcelos       1068.96       Furgão
41                 Nunes                  da Luz       1176.16      Carreta
42        Lopes Paulista      Barbosa das Flores        791.04     Caminhão
43              da Cunha        da Luz de Castro        886.99      Carreta
44        Machado do Sul  das Neves dos Dourados       2929.77     Caminhão
45               Pacheco         da Luz da Prata        113.19       Furgão
46        Brito de Souza          Souza de Minas       2447.82       Furgão
47                Aragão        Camargo da Prata       1596.15      Carreta
48                Vargas                Mendonça       1209.03     Caminhão
49          Brito Alegre         Moraes do Norte       1134.01     Caminhão

In [23]:
df_dropped.to_excel("Rotas_trat.xlsx", index=False)

: